### ISSUE TITLE
关于例子中命令行的使用问题

### ISSUE THREAD

**Issue by Southswallows** [dxjia/ffmpeg-jni-sample#1]
您好，
         按照您readme的说明，完成了ffmpeg的编译工作，也成功运行了您的例子。但是例子中的命令行，在cmdutils.c中没找到你实现方法的命令行说明。
         我要使用其他命令行，该如何操作，或者说阅读哪些文件，能知道命令行的使用方法。
         谢谢您，对代码的开源，对我有很大的帮助。
         希望您能给我解答。

**Comment by dxjia** [comment]
命令行是直接传递给jni的，你可以看一下ffmpeg-jni-sample的 MainActivity.java 里对 FFmpegNativeHelper的调用。
如果要使用其他命令行，只需要自己整理命令字串就可以了。ffmpeg支持的命令参数实在是太多，可以根据自己的需要网络上搜索，或者看ffmpeg的官方文档。 @Southswallows

**Comment by dxjia** [comment]
需要说明的是，我这里jni的代码都是ffmpeg的源码，只不过将程序main入口改为 jni native接口罢了，所以使用上是完全跟直接命令行调用 ffmpeg 可执行文件是一样的，并不是自己整理了一套命令行规则，所以只需要关注ffmpeg命令行怎么使用即可。@Southswallows

**Comment by Southswallows** [comment]
谢谢您的耐心解答
已经知道您的意思了
我去试试看

**Comment by dxjia** [comment]
close
