### ISSUE TITLE
根据runCommand返回值判断命令是否执行成功

### ISSUE THREAD

**Issue by jaycee88** [dxjia/ffmpeg-jni-sample#10]
FFmpegNativeHelper.runCommand执行成功的返回值是什么？谢谢！

**Comment by dxjia** [comment]
`runCommand` 目前是会返回一些执行后的字串，类似在 PC 上命令行内执行 ffmpeg 后得到的打印输出，无法给出明确的成功还是失败指示。
而如果传递给 `runCommand` 的命令执行后没有结果输出，那么 会依据有没有发生异常，给出 `SUCCESS` 或 `FAIL` 来表示结果。
