### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by kobeisgod** [dxjia/ffmpeg-jni-sample#2]
大神，step2 和step3能否写清楚点？我按照你另一个例子编译出来so库了，但是卡在step2和step3。就是如何将ffmpeg.c改为FFmpegNativeHelper.c那步，以及ndk-build的时候会提示h文件缺失，需要引入include外的ffmpeg源码中的h文件那个步骤。

**Comment by dxjia** [comment]
@kobeisgod 
是在linux下嘛？当时这个example是在linux下写的，
ffmpeg.c直接重命名为FFmpegNativeHelper.c， 将main函数改为jni接口即可。。。
缺少.h的问题，你在Android.arm.mk里加上这句试试：

```
LOCAL_C_INCLUDES += $(LOCAL_PATH)
```

理论上讲应该不需要这句，试试吧。。

**Comment by dxjia** [comment]
这会没有linux环境了,刚在windows下试了下,可以正常编译,不过需要修改一下Android.mk(已经上传了)，然后重要的是配置自己的eclipse的NDK编译环境。。。。。
你可以参考：http://blog.csdn.net/gf771115/article/details/12066887
还有，记得将NDK Builder排序靠前。。。

**Comment by kobeisgod** [comment]
我也是在linux下编译的。然后缺少h头文件的问题。我就去ffmpeg源码中拷贝那些头文件，include文件夹下和你项目中的一模一样了。这样ndk-build之后可以编译出八个so库。不过调用的时候crash。我看到项目中FFmpegNativeHelper.c是改造ffmpeg.c这个类的。我想请教下，ffmpeg.c这个类改动的地方有哪些，我已知的是ffmpeg.c中int main(...)改成了ffmpeg_main_entry(...)。我看其他两篇类似的博客说http://blog.csdn.net/leixiaohua1020/article/details/47056365 还要修改ffmpeg.c去掉一些exit(0),释放一些变量等等。我想问下，你有没有这步操作？只是修改main函数就可以了吗？其他两篇博客都讲的不太清楚T_T。我感觉对ffmpeg源码不熟悉，就只去修改main()函数就可以了。。

**Comment by kobeisgod** [comment]
http://bbs.rosoo.net/thread-13362-1-1.html  流媒体论坛中一个so库调用的帖子，也是说只需要修改main(..)。我刚看到close的issue中，你也说了只修改了main(...)。我想简单调用命令行应该就不用考虑exit(0)，释放变量这些，毕竟对ffmpeg源码比较熟悉的地方。我先继续尝试，只修改mian()方法也编译出了八个so库，可能其他地方出错了。
https://blog.crazyman.top/2015/05/06/%E7%BC%96%E8%AF%91ffmpeg/ 
以上是我接触的几篇博客，希望后面的人看到也可以有一些参考。
十分感谢dxjia :+1:

**Comment by dxjia** [comment]
确实需要拷贝头文件过来。
exit(0)的问题，以前我没有注意到，或许应该注释掉，否则每次命令执行完，都exit了？这应该是针对直接调用可执行程序的逻辑。。。

你贴的几篇 blog 都非常不错。。。
