### ISSUE TITLE
如何使用单一的libffmpeg.so文件进行链接呢？

### ISSUE THREAD

**Issue by futurexiong** [dxjia/ffmpeg-jni-sample#4]
我之前按照项目需求单独生成了libffmpeg.so，把你Android.mk里那一堆prebuild so的地方改成了
`include $(CLEAR_VARS)
LOCAL_MODULE := ffmpeg
LOCAL_SRC_FILES := prebuilt/armeabi/libffmpeg.so
include $(PREBUILT_SHARED_LIBRARY)`
其他不变，缺失的头文件也从源码里面拷到include里面了。
最后ndk-build的时候出现了一堆undefined引用
![image](https://cloud.githubusercontent.com/assets/1567478/15531572/9825d368-228d-11e6-9847-d2361c3dde97.png)
请问这个能如何解决呢？还是说我编译ffmpeg configure的时候必须选enable-shared？

**Comment by dxjia** [comment]
@futurexiong
你的 libffmpeg.so 是静态库？那样的话 改成 `include $(PREBUILT_STATIC_LIBRARY)` 试试。
因为我是以shared library的形式使用，所以 ffmpeg configure 必须 disable-static，并enable-shared了。

**Comment by futurexiong** [comment]
@dxjia 不是，因为我添加了x264和fdk-aac，所以是通过enable-static编译出所有object文件然后通过gcc链接成的动态库。本质上应该跟你分开8个so是没有区别的~我刚试了下没有理会x264和fdk-aac，编译出9个so库，检查修改了几次之后可以生成so了。show_function_wrapper.c是记录ffmpeg操作结果的？只有完全执行完了才返回吗？

**Comment by dxjia** [comment]
是的。
对一些命令的执行结果进行了记录，并在命令结束后通过jni返回给java层。不是很友好。
现在我觉得，如果是只单纯想让 ffmpeg 执行命令，还不如用 bin 可执行文件的方式来做，那样反而简单点。目前的实现方式觉得不是太好。

**Comment by futurexiong** [comment]
bin是没有问题的，也有一些库是通过Java层开Process执行executable，但是由于5.0强制要求executable是PIE格式的，所以如果要兼容4.1以下会导致需要打包2个executable然后根据版本拷贝。但对ffmpeg不是很了解，所以只能用so来执行命令了。有些文章的思路是通过写到文件当中然后Java层隔1-2秒判断文件变化读取文件内容，可以解决读取长时间执行过程的进度问题。

**Comment by dxjia** [comment]
你说的是 [这个](https://github.com/WritingMinds/ffmpeg-android-java) 吗? 貌似它是新开进程执行的；
我在 x86 的 6.0 设备上试了一下，可以跑，没细看它是怎么解决的。
不过体积好大，应该是 config 开的比较多。

**Comment by futurexiong** [comment]
对。还有个问题就是有方法终止命令行的执行吗？

**Comment by dxjia** [comment]
@futurexiong 
目前不支持。

**Comment by futurexiong** [comment]
ARM_CONFIG是哪来的呢。NDK编译的那几个C文件里的define，要跟so库里一样吧？

**Comment by dxjia** [comment]
就是ffmpeg 编译根据configure 生成的 config.h

**Comment by dxjia** [comment]
必须一致！
