### ISSUE TITLE
为什么运行命令找不到？h264??

### ISSUE THREAD

**Issue by zhuowh2006** [dxjia/ffmpeg-jni-sample#6]
ffmpeg -i K:/ffmpegtest/20160614104833_10.MP4 -vcodec h264 -s 320*240 -an -f mp4 K:/ffmpegtest/result_m4v.MP4

运行这段命令找不到h264？？还有好多命令都用吧了，但是widows版本的没问题，是不是少编译了东西

**Comment by zhuowh2006** [comment]
同样的命令在window下的版本可以运行，但是在编译的版本上就运行不了，报错说找不到这个命令关键字，用的是你这个版本

**Comment by dxjia** [comment]
使用的 ffmpeg 的编译 config 在 [这里](https://github.com/dxjia/ffmpeg-compile-shared-library-for-android)，感觉应该支持才对，具体错误log可以贴下吗？

**Comment by dxjia** [comment]
sorry, 使用`ffmpeg -encoders`看了一下，确实没有 h264 的编解码支持；
搜索了一下，这个需要额外移植 h264 到 ffmpeg 才可以。
暂不支持。

**Comment by zhuowh2006** [comment]
好的！谢谢！刚开始搞不懂什么原因！以为编译好了什么命令都能执行！现在好了！我自己编译了一个libx264

发自 网易邮箱大师
在2016年07月15日 02:59，dxjia 写道:

sorry, 使用ffmpeg -encoders看了一下，确实没有 h264 的编解码支持；
搜索了一下，这个需要额外移植 h264 到 ffmpeg 才可以。
暂不支持。
