### ISSUE TITLE
ffmpeg报“Out of memory”错误

### ISSUE THREAD

**Issue by xing5933** [dxjia/ffmpeg-jni-sample#8]
你好，我用ffmpeg处理视频压缩。
命令如下："ffmpeg -y -i " + url + " -strict experimental -r 20 -vcodec mpeg4 -b 10000 -s 640*480 /storage/emulated/0/abc.mp4"
第一次运行压缩成功，但是第二次运行就会报错，错误如下：
“ffmpeg-jni: [audio format for output stream 0:1 @ 0x9bef4960] Query format failed for 'audio format for output stream 0:1': Out of memory”
必须重启应用才可以再次压缩，然而也只能执行一次，第二次就报错了。

**Comment by dxjia** [comment]
Version? 
0.1.7 ?

**Comment by dxjia** [comment]
Close for no-response.
