### ISSUE TITLE
FFmpegNativeHelper.c 该文件是怎么生成的呢，我怎么生成的文件都带有 包名啊

### ISSUE THREAD

**Issue by tianshaokai** [dxjia/ffmpeg-jni-sample#9]
我是studio 项目，作者给说说 在 哪个目录执行 命令啊 生成 啊

**Comment by dxjia** [comment]
`FFmpegNativeHelper.c` 文件是从 `ffmpeg.c` 重命名而来，jni 请关注 method name，文件名无所谓。

**Comment by tianshaokai** [comment]
@dxjia 加下你qq吧，这么问你问题不方便
